#!/bin/bash

#  Churnometer - A dashboard for exploring a membership organisation's turn-over/churn
#  Copyright (C) 2012-2013 Lucas Rohde (freeChange)
#  lukerohde@gmail.com
#
#  Churnometer is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Churnometer is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with Churnometer.  If not, see <http://www.gnu.org/licenses/>.



DB_FILE="$2"
REPO="git@github.com:lukerohde/churnometer_base.git"
PRODUCTION_BRANCH="master"
DB_REPO="git@github.com:lukerohde/churnometer_data.git"

WWW_PATH="${APP_PATH-/opt/churnometer}"
CHURN_USER="${CHURN_USER-churnometer}"
CHURN_PASS="${CHURN_PASS-password}"
PG_VERSION="${PG_VERSION-9.6}"
PG_PATH="/etc/postgresql/${PG_VERSION}/main"

pwdir=$(pwd)

function confirm_config
{
  while [[ "$CONFIRMED" != "Y" && "$CONFIRMED" != "y" ]] ; do
    echo "***********************************************************************"
    echo "* CONFIRM CONFIG"
    echo "*"
    echo "*"
    echo "***********************************************************************"
    echo "Database and application user: $CHURN_USER"
    echo "Database and application user's password: $CHURN_PASS"
    echo "Installation directory for application source: $WWW_PATH"
    echo "Directory of Postgres ${PG_VERSION} configuration (will be overwritten!!!): $PG_PATH"
    echo "Source download repository: $REPO"
    echo "Branch in source download repository: $PRODUCTION_BRANCH"
    if [[ ! ${DB_FILE} ]] ; then
      echo "You haven't specified a database backup file that exists.  Demo data download repository: $DB_REPO"
    else
      echo "DB backup file to restore from: $DB_FILE"
    fi

    read -e -i "Y" -p "Is this configuration correct [Y/N]? " CONFIRMED

    if  [[ $CONFIRMED != "Y" && $CONFIRMED != "y" ]] ; then
      read -e -i "$CHURN_USER" -p "Please enter a username for the database and webservice: " CHURN_USER
      read -e -i "$CHURN_PASS" -p "Please enter a password for user $CHURN_USER: " CHURN_PASS
      read -e -i "$WWW_PATH" -p "Please enter a path to install the application: " WWW_PATH
      read -e -i "$PG_PATH" -p "Please confirm the path to your postgres configuration (only tested with 9.1 and will overwrite!): " PG_PATH
      read -e -i "$REPO" -p "Please confirm the repository from which you to download the source: " REPO
      read -e -i "$PRODUCTION_BRANCH" -p "Please confirm the branch of $REPO: " PRODUCTION_BRANCH
      if [[ ! ${DB_FILE} ]] ; then
        read -e -i "$DB_REPO" -p "Please confirm the repository from which to download the demo data: " DB_REPO
      fi
    fi
  done
}

function install
{
  echo "***********************************************************************"
  echo "* INSTALLING SOFTWARE DEPENDENCIES"
  echo "*"
  echo "*"
  echo "***********************************************************************"

  sudo apt-get update

  sudo apt-get -y install postgresql libpq-dev git build-essential sendmail libxml2-dev libxslt-dev nginx zip libreadline-dev
}

function churn_user
{
  echo "***********************************************************************"
  echo "* CREATING USER"
  echo "*"
  echo "*"
  echo "***********************************************************************"

  sudo useradd -d /home/$CHURN_USER -m $CHURN_USER # -p option for setting password doesn't work
  sudo bash -c "echo \"$CHURN_USER:$CHURN_PASS\" | chpasswd" # set password
  sudo usermod -s /bin/bash $CHURN_USER # set up bash shell
  sudo usermod -a -G sudo $CHURN_USER # allow sudo
  sudo bash -c "echo AllowUsers $CHURN_USER >> /etc/ssh/sshd_config" # allow ssh
  sudo /etc/init.d/ssh restart

  sudo -u $CHURN_USER ssh-keygen -t rsa -b 4096 -f /home/$CHURN_USER/.ssh/id_rsa -N ""
  echo -e "\n\nCopy this key to https://github.com/account/ssh"
  echo -e "- To download the source you'll need to be a collaborator on $REPO (if it isn't public)"
  echo -e "- To download the demo data you'll need to be a collaborator on $DB_REPO (if it isn't public)"
  echo -e "\n"
  sudo -u $CHURN_USER cat /home/$CHURN_USER/.ssh/id_rsa.pub
  echo -e '\nPress enter once done'
  read
}


function source_config
{

  echo "***********************************************************************"
  echo "* INSTALLING SOURCE CODE"
  echo "*"
  echo "*"
  echo "***********************************************************************"

  sudo -u $CHURN_USER /etc/init.d/thin stop # stop thin before tmp/pids are deleted (in case of reinstall)
  sudo rm -Rf $WWW_PATH
  sudo mkdir $WWW_PATH
  sudo chown $CHURN_USER $WWW_PATH

  sudo -u $CHURN_USER rm /home/$CHURN_USER/www
  sudo -u $CHURN_USER ln -s $WWW_PATH /home/$CHURN_USER/www

  cd $WWW_PATH
  sudo -u $CHURN_USER git clone $REPO $WWW_PATH
  sudo -u $CHURN_USER git checkout $PRODUCTION_BRANCH

  sudo -u $CHURN_USER cp config/config_site.yaml.example config/config_site.yaml

  sudo -u $CHURN_USER bash -c " \
    sed \"s|REPLACEME_CHURN_USER|$CHURN_USER|g\" $WWW_PATH/config/config_site.yaml.example \
    | sed \"s|REPLACEME_CHURN_PASS|$CHURN_PASS|g\" \
    | sed \"s|REPLACEME_SOURCE_REPO|$REPO |g\" \
    > $WWW_PATH/config/config_site.yaml"

  sudo -u $CHURN_USER vim config/config_site.yaml
  #sudo -u $CHURN_USER mkdir $WWW_PATH/uploads
  sudo -u $CHURN_USER mkdir $WWW_PATH/tmp
  sudo -u $CHURN_USER mkdir $WWW_PATH/log
  sudo -u $CHURN_USER mkdir $WWW_PATH/backup

  sudo git config --system user.email "$USER@$HOSTNAME"
  sudo git config --system user.name "$USER"
}


function db_config
{
  echo "***********************************************************************"
  echo "* CONFIGURING POSTGRESQL DATABASE"
  echo "*"
  echo "*"
  echo "***********************************************************************"
  if [ -f ${PG_PATH}/postgresql.conf.bak ] ; then
    read -e -i "Y" -p "Overwrite ${PG_PATH}/postgresql.conf.bak with current config [Y/N]? " CONFIRMED
    if  [[ $CONFIRMED != "Y" && $CONFIRMED != "y" ]] ; then
      sudo bash -c "mv ${PG_PATH}/postgresql.conf ${PG_PATH}/postgresql.conf.bak"
    fi
  fi

  sudo bash -c "cp ${WWW_PATH}/config/postgresql.conf.${PG_VERSION}.example ${PG_PATH}/postgresql.conf"
  sudo bash -c "echo -e '\n #remote admin access'  >> ${PG_PATH}/pg_hba.conf"
  sudo bash -c "echo -e 'hostssl\tall\t\tall\t\t\t0.0.0.0/0\tmd5' >> ${PG_PATH}/pg_hba.conf"
#https://wiki.postgresql.org/wiki/Tuning_Your_PostgreSQL_Server
#https://www.postgresql.org/docs/9.6/static/kernel-resources.html
  sudo sysctl -w kernel.shmmax=1073741824
  sudo sysctl -w kernel.shmall=262144
  sudo bash -c "echo kernel.shmmax=1073741824 | tee -a /etc/sysctl.conf"
  sudo bash -c "echo kernel.shmall=262144 | tee -a /etc/sysctl.conf"

  sudo bash -c "echo PGDATESTYLE=european >> /etc/environment" #I'm not sure I want to keep this but it interprets dates as dd/mm/yyyy
  sudo /etc/init.d/postgresql restart
}

function db_import
{
  echo "***********************************************************************"
  echo "* IMPORTING DATA"
  echo "*"
  echo "*"
  echo "***********************************************************************"

  if [[ ! ${DB_FILE} ]] ; then
    DB_FILE="/home/$CHURN_USER/churnometer_temp/sql/churnometer_base.sql"
    if [[ ! -f ${DB_FILE} ]] ; then
      sudo -u $CHURN_USER git clone $DB_REPO /home/$CHURN_USER/churnometer_temp/
    fi
  fi

  sudo -u postgres psql -c "create user ${CHURN_USER} with password '${CHURN_PASS}'"
  sudo -u postgres psql -c "drop database churnometer"
  sudo -u postgres psql -c "create database churnometer"
  cd $pwdir # incase a relative path was specified to database
  sudo -u postgres psql churnometer < $DB_FILE
}

function ruby_config
{
  echo "***********************************************************************"
  echo "* INSTALLING RUBY"
  echo "*"
  echo "*"
  echo "***********************************************************************"

  sudo su - $CHURN_USER <<EOF
    git clone https://github.com/rbenv/rbenv.git ~/.rbenv
    git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
    echo 'PATH="/home/$CHURN_USER/.rbenv/bin:/home/$CHURN_USER/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.profile
    echo 'export PATH="/home/$CHURN_USER/.rbenv/bin:/home/$CHURN_USER/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
    echo 'eval "\$(rbenv init -)"' >> ~/.bashrc
    echo '[[ -r ~/.bashrc ]] && . ~/.bashrc' >> .bash_profile
EOF

  sudo su - $CHURN_USER -c 'rbenv install 2.3.3'
  sudo su - $CHURN_USER -c 'rbenv global 2.3.3'
  sudo su - $CHURN_USER -c 'rbenv exec ruby -v'

  echo "***********************************************************************"
  echo "* INSTALLING GEMS"
  echo "*"
  echo "*"
  echo "***********************************************************************"
  sudo su - $CHURN_USER <<EOF
    cd $WWW_PATH
    rbenv exec gem install bundler
    rbenv exec bundle install
EOF
}

function daemonise
{
  echo "***********************************************************************"
  echo "* DAEMONISING CHURNOMETER"
  echo "*"
  echo "*"
  echo "***********************************************************************"

  sed "s|REPLACEME_WWW_PATH|$WWW_PATH|g" $WWW_PATH/config/churnometer.service.example \
  | sed "s|REPLACEME_CHURN_USER|$CHURN_USER|g" > ~/churnometer.service.tmp

  sudo cp ~/churnometer.service.tmp /etc/systemd/system/churnometer.service

  sed "s|REPLACEME_WWW_PATH|$WWW_PATH|g" \
    $WWW_PATH/config/nginx_site.conf.example \
    > ~/nginx.conf.tmp

  sudo mv ~/nginx.conf.tmp /etc/nginx/sites-available/churnometer.conf
  sudo ln -s /etc/nginx/sites-available/churnometer.conf \
    /etc/nginx/sites-enabled/churnometer.conf

  sudo rm /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
  sudo systemctl start churnometer
  sudo systemctl daemon-reload
  sudo /etc/init.d/nginx restart

  # allow churn user to restart churnometer service without password
  sed "s|REPLACEME_CHURN_USER|$CHURN_USER|g" \
    $WWW_PATH/config/restart_churnometer_sudoer.example \
    > ~/restart_churnometer_sudoer.tmp
  sudo mv ~/restart_churnometer_sudoer.tmp /etc/sudoers.d/restart_churnometer
}

function samba
{
  echo "***********************************************************************"
  echo "* INSTALLING WINDOWS SHARE"
  echo "*"
  echo "*"
  echo "***********************************************************************"

  sudo bash -c "(echo $CHURN_PASS; echo $CHURN_PASS) | smbpasswd -s -a $CHURN_USER"

  sudo /etc/init.d/smbd restart
}

case $1 in
  just-software)
    confirm_config
    install
  ;;
  just-user)
    confirm_config
    churn_user
  ;;
  just-source)
    confirm_config
    source_config
  ;;
  just-dbconfig)
    confirm_config
    db_config
  ;;
  just-data)
    confirm_config
    db_import
  ;;
  just-gems)
    confirm_config
    ruby_config
  ;;
  just-daemonise)
    confirm_config
    daemonise
  ;;
  just-samba)
    confirm_config
    samba
  ;;
  install)
    confirm_config
    churn_user
    install
    source_config
    db_config
    db_import
    ruby_config
    samba
    daemonise
  ;;
  *)
    echo >&2 "Usage: $0 < install | just-samba | just-software | just-user | just-source | just-dbconfig | just-data | just-gems | just-daemonise > [db backup file]"
    exit 1
    ;;
esac
#  Churnometer - A dashboard for exploring a membership organisation's turn-over/churn
#  Copyright (C) 2012-2013 Lucas Rohde (freeChange)
#  lukerohde@gmail.com
#
#  Churnometer is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
