# This is our production compose file - not changed for docker-sync or similar

version: "3"
services:
  db:
    build:
      context: .
      dockerfile: dockerfile-db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "50"
        max-size: "10m"
    volumes:
      - pgdata:/pgdata:delegated
      - $PWD/db-setup.sql:/docker-entrypoint-initdb.d/db-setup.sql
      - $PWD/scripts/db:/scripts
    environment:
      - PGDATA=/pgdata
      - CHURN_USER
      - CHURN_PASS
      - PGDATESTYLE
  www:
    build:
      context: .
      dockerfile: dockerfile-www
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "50"
        max-size: "10m"
    volumes:
      - bundle:/usr/local/bundle
      - $PWD/app:/app
    environment:
      - BUNDLE_PATH=/usr/local/bundle
      - GEM_HOME=/usr/local/bundle
      - RACK_ENV
      - CHURN_USER
      - CHURN_PASS
      - PGDATESTYLE
      - OAUTH2_CLIENT_ID
      - OAUTH2_CLIENT_SECRET
      - OAUTH2_CLIENT_REDIRECT_URI
      - OAUTH2_PROVIDER
      - LDAP_ADMIN_GROUP
      - EXPORT_CUTOFF
    links:
      - db
    command: ./docker-command
volumes:
  bundle:
  pgdata:
