FROM ruby:2.7.4

RUN apt-get update
RUN apt-get -y install postgresql-client libpq-dev git build-essential sendmail libxml2-dev libxslt-dev zip libreadline-dev vim

ENV APP /app
RUN mkdir $APP
WORKDIR $APP
COPY ./app $APP
#Using .keep files for these dirs
#RUN mkdir -p $APP/tmp
#RUN mkdir -p $APP/log
#RUN mkdir -p $APP/backup
#RUN mkdir -p $APP/pids
