FROM postgres:18
COPY ./app/config/seed.sql.gz ./seed.sql.gz
COPY ./docker-seed /docker-entrypoint-initdb.d/10-seed.sh

CMD ["postgres", "-c", "hba_file=/pg_hba.conf", "-c", "config_file=/etc/postgresql.conf"]
