#!/bin/bash

cd $1

git filter-branch --index-filter "git rm --cached --ignore-unmatch \"$2\"" \
  -f --prune-empty --tag-name-filter cat -- --all

rm -rf .git/refs/original/
git reflog expire --expire=now --all
git gc --prune=now
git gc --aggressive --prune=now
