#!/bin/bash
# https://help.github.com/articles/remove-sensitive-data

purging "$1"

git filter-branch --force --index-filter \
"git rm --cached --ignore-unmatch \"$1\"" \
--prune-empty --tag-name-filter cat -- --all

#echo $1 >> .git_ignore
#git add .gitignore
#git commit -m "Add $1 to .gitignore"

#rm -rf .git/refs/original/
#git reflog expire --expire=now --all
#git gc --prune=now
#git gc --aggressive --prune=nowi

#git for-each-ref --format='delete %(refname)' refs/original | git update-ref --stdin
#git reflog expire --expire=now --all
#git gc --prune=now
