#!/bin/sh
echo "Ensuring bundler installed"
gem install bundler:1.14.6

echo "Bundling gems"
bundle check || bundle install --jobs 4 --retry 3

echo "Removing old Puma and temp files"
rm pids/*
rm tmp/*

echo "Starting puma"
bundle exec puma
