source "http://rubygems.org"

gem 'sinatra', '~> 1.4.0'
gem 'sinatra-contrib'
gem 'pg'
gem 'sass'
gem 'spreadsheet'
gem 'shotgun'
gem 'tilt'
gem 'ruby-ole', '~> 1.2', '>= 1.2.12'
gem 'money', '3.7.1'
gem 'addressable'
gem 'pony'
gem 'puma'
gem 'nokogiri'
gem 'oauth2'
#gem 'rack-auth-kerberos'

gem 'pry-byebug'

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'launchy'
end
