#!/bin/bash
#
# init.d script for single or multiple ruby installations. Expects at least one .conf 
# file in /etc/ruby
#
# Modified by jay@gooby.org http://github.com/jaygooby
# based on http://gist.github.com/308216 by http://github.com/mguterl
#
## A sample /etc/ruby/my_app.conf
## 
## RAILS_ENV=production
CHURNOMETER_ROOT=/opt/churnometer
#
# This configures a ruby master for your app at /var/apps/www/my_app/current running in
# production mode. It will read config/ruby.rb for further set up. 
#
# You should ensure different ports or sockets are set in each config/ruby.rb if
# you are running more than one master concurrently.
#
# If you call this script without any config parameters, it will attempt to run the
# init command for all your ruby configurations listed in /etc/ruby/*.conf
#
# /etc/init.d/ruby start # starts all rubys
#
# If you specify a particular config, it will only operate on that one
#
# /etc/init.d/ruby start /etc/ruby/my_app.conf

set -e

sig () {
  test -s "$PID" && kill -$1 `cat "$PID"`
}

oldsig () {
  test -s "$OLD_PID" && kill -$1 `cat "$OLD_PID"`
}

cmd () {

  case $1 in
    start)
      sig 0 && echo >&2 "Already running" && exit 0
      echo "Starting"
      $CMD &
      sudo -u churnometer bash -c "echo $! > $CHURNOMETER_ROOT/tmp/churnometer.pid"
      ;;  
    stop)
      sig QUIT && echo "Stopping" && exit 0
      echo >&2 "Not running"
      ;;  
    force-stop)
      sig TERM && echo "Forcing a stop" && exit 0
      echo >&2 "Not running"
      ;;  
    restart|reload)
      sig USR2 && sleep 5 && oldsig QUIT && echo "Killing old master" `cat $OLD_PID` && exit 0
      echo >&2 "Couldn't reload, starting '$CMD' instead"
      $CMD &
      ;;  
    *)  
      echo >&2 "Usage: $0 <start|stop|restart|force-stop>"
      exit 1
      ;;  
    esac
}

setup () {

  echo -n "$CHURNOMETER_ROOT: "  
  cd $CHURNOMETER_ROOT || exit 1
  export PID=$CHURNOMETER_ROOT/tmp/churnometer.pid
  export OLD_PID="$PID.oldbin"
  if [[ ! -d $CHURNOMETER_ROOT/tmp ]] ; then 
    sudo -u churnometer mkdir $CHURNOMETER_ROOT/tmp
  fi

  CMD="sudo privbind -u churnometer thin start --threaded -p 80"
}

start_stop () {
  setup
  cmd $1
}

ARGS="$1"
start_stop $ARGS
