#!/bin/bash
#
# init.d script for single churnometer installations.
#
# Modified from a script by jay@gooby.org http://github.com/jaygooby
# based on http://gist.github.com/308216 by http://github.com/mguterl
#
CHURNOMETER_ROOT=REPLACEME_WWW_PATH
CHURNUSER=REPLACEME_CHURN_USER
#
# /etc/init.d/churnometer start

set -e

sig () {
  test -s "$PID" && kill -$1 `cat "$PID"`
}

oldsig () {
  test -s "$OLD_PID" && kill -$1 `cat "$OLD_PID"`
}

cmd () {

  case $1 in
    start)
      sig 0 && echo >&2 "Already running" && exit 0
      echo "Starting"
      $CMD &
      sudo -u $CHURNUSER bash -c "echo $! > $CHURNOMETER_ROOT/tmp/churnometer.pid"
      ;;  
    stop)
      sig QUIT && echo "Stopping" && exit 0
      echo >&2 "Not running"
      ;;  
    force-stop)
      sig TERM && echo "Forcing a stop" && exit 0
      echo >&2 "Not running"
      ;;  
    restart|reload)
      sig USR2 && sleep 5 && oldsig QUIT && echo "Killing old master" `cat $OLD_PID` && exit 0
      echo >&2 "Couldn't reload, starting '$CMD' instead"
      $CMD &
      ;;  
    *)  
      echo >&2 "Usage: $0 <start|stop|restart|force-stop>"
      exit 1
      ;;  
    esac
}

setup () {

  echo -n "$CHURNOMETER_ROOT: "  
  cd $CHURNOMETER_ROOT || exit 1
  export PID=$CHURNOMETER_ROOT/tmp/churnometer.pid
  export OLD_PID="$PID.oldbin"
  if [[ ! -d $CHURNOMETER_ROOT/tmp ]] ; then 
    sudo -u $CHURNUSER mkdir $CHURNOMETER_ROOT/tmp
  fi

  CMD="sudo privbind -u $CHURNUSER thin start --threaded -p 80"
}

start_stop () {
  setup
  cmd $1
}

ARGS="$1"
start_stop $ARGS
